services:
  mysql:
    image: mysql:8.0
    container_name: 2024SPARCS_MySQL
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: dev_db
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - my_network

networks:
  my_network:
    driver: bridge